### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by 02874712** [02874712/Calendar#1]
- [x] Construct the Layout of the Todo List Screen
- [x] Add items to the Todo List 
   - [x] User can view list after exiting and returning to the app
- [x] Modify a task
