### ISSUE TITLE
Todo List Pt. 2

### ISSUE THREAD

**Issue by 02874712** [02874712/Calendar#3]
- [x] Setup the RecyclerView
   - [x] Setup the adapter for the RecyclerView
- [ ] Mark tasks as completed
